"""create celery_task_executions table

Revision ID: c60349bab822
Revises: 3a8911c3e29b
Create Date: 2026-04-08 16:49:10.187736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c60349bab822'
down_revision: Union[str, None] = '3a8911c3e29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_args_hash', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    op.create_index('ixz_task_execution_created_at', 'celery_task_executions', ['created_at'], unique=False)
    op.create_index('ixz_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixz_task_name_args_celery_hash', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_status', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_created_at', table_name='celery_task_executions')
    op.drop_index('ixz_celery_task_id', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    # ### end Alembic commands ###
